---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-victoria-metrics-victoria-metrics-single-clusterrole
  labels:
    helm.sh/chart: victoria-metrics-single-0.9.3
    app.kubernetes.io/managed-by: Helm
rules:
