---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-victoria-metrics-victoria-metrics-single-clusterrolebinding
  labels:
    helm.sh/chart: victoria-metrics-single-0.9.3
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: test-victoria-metrics-victoria-metrics-single
    namespace: homelab-apps
roleRef:
  kind: ClusterRole
  name: test-victoria-metrics-victoria-metrics-single-clusterrole
  apiGroup: rbac.authorization.k8s.io
