---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: victoria-metrics-victoria-metrics-single-server
  namespace: taylor-monitoring
  labels: 
    app: server
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/version: v1.136.0
    helm.sh/chart: victoria-metrics-single-0.31.0
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
