---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-victoria-metrics-single-server
  namespace: taylor-monitoring
  labels: 
    app: server
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/version: v1.136.0
    helm.sh/chart: victoria-metrics-single-0.31.0
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels: 
      app: server
      app.kubernetes.io/instance: victoria-metrics
      app.kubernetes.io/name: victoria-metrics-single
  template:
    metadata:
      labels: 
        app: server
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-single
        app.kubernetes.io/version: v1.136.0
        helm.sh/chart: victoria-metrics-single-0.31.0
    spec:
      serviceAccountName: victoria-metrics-victoria-metrics-single-server
      automountServiceAccountToken: true
      securityContext: 
        {}
      containers:
        - name: vmsingle
          securityContext: 
            {}
          image: victoriametrics/victoria-metrics:v1.136.0
          imagePullPolicy: IfNotPresent
          args: 
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8428
            - --loggerFormat=json
            - --retentionPeriod=72
            - --storageDataPath=/storage
          ports:
            - name: http
              containerPort: 8428
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 5
          volumeMounts:
            - name: server-volume
              mountPath: /storage
            
      terminationGracePeriodSeconds: 60
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: victoria-metrics-victoria-metrics-single-server
