---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: test-taylor-monitoring
  labels: 
    app: server
    app.kubernetes.io/instance: test-victoria-metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/version: v1.136.0
    helm.sh/chart: victoria-metrics-single-0.31.0
  name: test-victoria-metrics-victoria-metrics-single-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: http
  selector: 
    app: server
    app.kubernetes.io/instance: test-victoria-metrics
    app.kubernetes.io/name: victoria-metrics-single
