---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: victoria-metrics-single-0.9.3
    app.kubernetes.io/managed-by: Helm
  name: victoria-metrics-victoria-metrics-single
  namespace: taylor-monitoring
