---
# Source: victoria-metrics-taylor/charts/victoria-metrics-single/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: 
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: victoria-metrics-single-0.31.0
  name: victoria-metrics-victoria-metrics-single-server
  namespace: taylor-monitoring
