---
# Source: home-assistant/charts/home-assistant/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-home-assistant
  labels:
    helm.sh/chart: home-assistant-0.3.43
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: test-home-assistant
    app.kubernetes.io/version: "2026.2.1"
    app.kubernetes.io/managed-by: Helm
