---
# Source: home-assistant/charts/home-assistant/templates/service-codeserver.yaml
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-codeserver
  labels:
    helm.sh/chart: home-assistant-0.3.28
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/version: "2025.10.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 12321
      targetPort: codeserver
      protocol: TCP
      name: codeserver
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
