---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frigate
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-frigate
spec:
  destination:
    name: in-cluster
    namespace: frigate
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-grafana-scott
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-grafana-scott
spec:
  destination:
    name: in-cluster
    namespace: scott-monitoring
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/grafana-scott
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-grafana-taylor
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-grafana-taylor
spec:
  destination:
    name: in-cluster
    namespace: taylor-monitoring
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/grafana-taylor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-home-assistant
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-kargo-config
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-kargo-config
spec:
  destination:
    name: in-cluster
    namespace: homelab-apps
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/kargo-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mosquitto-taylor
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-mosquitto-taylor
spec:
  destination:
    name: in-cluster
    namespace: taylor-monitoring
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/mosquitto-taylor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: application-generator/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mosquitto
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:prod-mosquitto
spec:
  destination:
    name: in-cluster
    namespace: mosquitto
  project: apps
  source:
    directory:
      recurse: true
    path: deploy/
    repoURL: https://github.com/syoder89-homelab/homelab-apps
    targetRevision: env/prod/mosquitto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
