---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-frigate
  namespace: homelab-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: frigate
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-apps
      - name: targetBranch
        value: env/prod/frigate
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/frigate/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: frigate
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/frigate-values.yaml
          #- ${{ vars.path_src }}/applications/frigate/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: frigate
          namespace: frigate
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/frigate
          outPath: ${{ vars.path_out }}/deploy/frigate
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/frigate
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-home-assistant
  namespace: homelab-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: home-assistant
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-apps
      - name: targetBranch
        value: env/prod/home-assistant
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/home-assistant/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: home-assistant
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/home-assistant-values.yaml
          #- ${{ vars.path_src }}/applications/home-assistant/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: home-assistant
          namespace: home-assistant
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/home-assistant
          outPath: ${{ vars.path_out }}/deploy/home-assistant
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/home-assistant
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-kargo-config
  namespace: homelab-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-config
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-apps
      - name: targetBranch
        value: env/prod/kargo-config
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/kargo-config/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: kargo-config
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/kargo-config-values.yaml
          #- ${{ vars.path_src }}/applications/kargo-config/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: kargo-config
          namespace: homelab-apps
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/kargo-config
          outPath: ${{ vars.path_out }}/deploy/kargo-config
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/kargo-config
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-mosquitto-taylor
  namespace: homelab-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: mosquitto-taylor
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-apps
      - name: targetBranch
        value: env/prod/mosquitto-taylor
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/mosquitto-taylor/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: mosquitto-taylor
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/mosquitto-taylor-values.yaml
          #- ${{ vars.path_src }}/applications/mosquitto-taylor/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: mosquitto
          namespace: taylor-monitoring
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/mosquitto-taylor
          outPath: ${{ vars.path_out }}/deploy/mosquitto-taylor
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/mosquitto-taylor
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-mosquitto
  namespace: homelab-apps
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: mosquitto
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-apps
      - name: targetBranch
        value: env/prod/mosquitto
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/platform
      - uses: copy
        config:
          inPath: ${{ vars.path_src }}/applications/mosquitto/config
          outPath: ${{ vars.path_src }}/charts/config-generator/config/application
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: ${{ vars.path_src }}/charts/config-generator
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: stageName
              value: prod
            - key: envType
              value: prod
            - key: appName
              value: mosquitto
          #valuesFiles:
          #- ${{ vars.path_src }}/config/prod/mosquitto-values.yaml
          #- ${{ vars.path_src }}/applications/mosquitto/values/prod.yaml
      - uses: helm-template
        config:
          releaseName: mosquitto
          namespace: mosquitto
          buildDependencies: true
          includeCRDs: true
          path: ${{ vars.path_src }}/applications/mosquitto
          outPath: ${{ vars.path_out }}/deploy/mosquitto
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/prod/mosquitto
