---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: frigate
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/frigate
      # Alternate config strategy
      #- stages/**/frigate-values.yaml
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana-scott
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/grafana-scott
      # Alternate config strategy
      #- stages/**/grafana-scott-values.yaml
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: home-assistant
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/home-assistant
      # Alternate config strategy
      #- stages/**/home-assistant-values.yaml
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-config
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/kargo-config
      # Alternate config strategy
      #- stages/**/kargo-config-values.yaml
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: mosquitto-taylor
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/mosquitto-taylor
      # Alternate config strategy
      #- stages/**/mosquitto-taylor-values.yaml
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: mosquitto
  namespace: homelab-apps
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      repoURL: https://github.com/syoder89-homelab/homelab-apps.git
      includePaths:
      - applications/mosquitto
      # Alternate config strategy
      #- stages/**/mosquitto-values.yaml
