---
# Source: influxdb-scott/charts/influxdb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
  labels:
    helm.sh/chart: influxdb-4.12.0
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/version: "1.8.10"
    app.kubernetes.io/managed-by: Helm
