---
# Source: influxdb-scott/charts/influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-influxdb
  labels:
    helm.sh/chart: influxdb-4.12.5
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: test-influxdb
    app.kubernetes.io/version: "1.8.10"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8086
    targetPort: api
  - name: rpc
    port: 8088
    targetPort: rpc
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: test-influxdb
