---
# Source: frigate/charts/frigate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frigate
  labels:
    app.kubernetes.io/name: frigate
    helm.sh/chart: frigate-7.0.3
    app.kubernetes.io/instance: test-frigate
    app.kubernetes.io/version: "0.12.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate
      app.kubernetes.io/instance: test-frigate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate
        app.kubernetes.io/instance: test-frigate
      annotations:
        checksum/configmap: b55a2b106e476fbefef2364d18e40880e67ec56883e75be75a9cfa3fa59cb548
    spec:
      initContainers:
        - name: copy-config
          image: busybox:1.28
          command: ["/bin/sh", "-c", "mv /config/config.yml /config/config.yml.old; cat /static-config/config.yml > /config/config.yml"]
          volumeMounts:
           - mountPath: /config
             name: config
           - mountPath: /static-config
             name: config-yml
      containers:
        - name: frigate
          image: "ghcr.io/blakeblackshear/frigate:0.12.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-auth
              containerPort: 8971
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: go2rtc-admin
              containerPort: 1984
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            - name: CONFIG_FILE
              value: "/config/config.yml"
          envFrom:
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
          resources:
      volumes:
        - name: config-yml
          configMap:
            name: test-frigate
        - name: config
          persistentVolumeClaim:
            claimName: test-frigate-config
        - name: media
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
