{{- range $path, $_ := .Files.Glob "applications/*/Chart.yaml" }}
{{- $app := $.Files.Get $path | fromYaml }}
{{- range $stage_name, $stage := $.Values.stages }}
{{- if $stage.isEphemeral }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral-{{ $stage_name }}-{{ $app.name }}
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: homelab-apps:{{ $stage_name }}-{{ $app.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: syoder89-homelab
        # The Github repository
        repo: homelab-apps
        tokenRef:
          secretName: argocd-github-pat
          key: token
      filters:
      - targetBranchMatch: "^{{ $stage.targetBranch }}/{{ $app.name }}$"
      requeueAfterSeconds: 60
      values:
        appName: "pr-{{`{{ .number }}`}}-{{ $stage_name }}-{{ $app.name }}"
        appNamespace: "pr-{{`{{ .number }}`}}-{{ $app.namespace | default $app.name }}"
  template:
    metadata:
      name: "{{`{{ .values.appName }}`}}"
      namespace: argocd
      annotations:
        kargo.akuity.io/authorized-stage: homelab-apps:{{ $stage_name }}-{{ $app.name }}
    spec:
      destination:
        name: in-cluster
        namespace: "{{`{{ .values.appNamespace }}`}}"
      project: apps
      source:
        directory:
          recurse: true
        path: deploy/
        repoURL: https://github.com/syoder89-homelab/homelab-apps
        targetRevision: "{{`{{ .head_sha }}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/instance: "{{`{{ .values.appName }}`}}"
          annotations:
            argocd.argoproj.io/tracking-id: >-
              "{{`{{ .values.appName }}`}}":apps/Namespace:{{`{{ .values.appNamespace }}`}}/{{`{{ .values.appNamespace }}`}}"
        syncOptions:
        - CreateNamespace=true
{{- end }}
{{- end }}
{{- end }}