---
# Source: home-assistant/templates/codeserver-credentials.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: home-assistant-codeserver-credentials
spec:
  itemPath: "vaults/homelab/items/home-assistant-codeserver-credentials"
