envs:
  prod:
    sources:
      # direct: true
      stages:
      - test-{{ .app.name }}
    asPR: true
    isEphemeral: false
    targetBranch: env/prod
    envType: prod
  test:
    sources:
      direct: true
    asPR: true
    isEphemeral: true
    targetBranch: env/test
    envType: test