---
# Source: grafana-scott/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-10.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-scott
    app.kubernetes.io/version: "12.2.0"
  name: grafana-scott-clusterrole
rules: []
