---
# Source: grafana-scott/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-10.4.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
    app.kubernetes.io/version: "12.3.1"
  name: test-grafana-scott-clusterrole
rules: []
