---
# Source: grafana-scott/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-scott-clusterrolebinding
  labels:
    helm.sh/chart: grafana-10.4.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-scott
    app.kubernetes.io/version: "12.3.1"
subjects:
  - kind: ServiceAccount
    name: grafana-scott
    namespace: scott-monitoring
roleRef:
  kind: ClusterRole
  name: grafana-scott-clusterrole
  apiGroup: rbac.authorization.k8s.io
