---
# Source: grafana-scott/charts/grafana/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-grafana-scott
  namespace: test-scott-monitoring
  labels:
    helm.sh/chart: grafana-10.5.15
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
    app.kubernetes.io/version: "12.3.1"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: openebs-storage-persist
