---
# Source: grafana-scott/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-scott
  namespace: scott-monitoring
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-scott
    app.kubernetes.io/version: "12.3.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-scott
subjects:
- kind: ServiceAccount
  name: grafana-scott
  namespace: scott-monitoring
