---
# Source: grafana-scott/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-grafana-scott
  namespace: test-scott-monitoring
  labels:
    helm.sh/chart: grafana-10.4.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
    app.kubernetes.io/version: "12.3.1"
rules: []
