---
# Source: grafana-scott/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-scott
  namespace: scott-monitoring
  labels:
    helm.sh/chart: grafana-10.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-scott
    app.kubernetes.io/version: "12.2.0"
rules: []
