---
# Source: grafana-scott/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-scott
  namespace: scott-monitoring
  labels:
    helm.sh/chart: grafana-10.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-scott
    app.kubernetes.io/version: "12.2.0"
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "dFZNeUoxNEQybUkzVWtPblN2SldLUHQ1OHFDallVdEkwTWt5cmNqUQ=="
  ldap-toml: ""
