---
# Source: grafana-scott/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-grafana-scott
  namespace: test-scott-monitoring
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
    app.kubernetes.io/version: "12.3.0"
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: grafana
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
