---
# Source: grafana-scott/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana-scott
    app.kubernetes.io/version: "12.3.0"
  name: test-grafana-scott
  namespace: test-scott-monitoring
