---
# Source: victoria-metrics-scott/charts/victoria-metrics-single/templates/server.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-victoria-metrics-scott-victoria-metrics-single-server
  namespace: test-scott-monitoring
  labels: 
    app: server
    app.kubernetes.io/instance: test-victoria-metrics-scott
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/version: v1.136.0
    helm.sh/chart: victoria-metrics-single-0.31.0
spec:
  podManagementPolicy: OrderedReady
  updateStrategy: {}
  replicas: 1
  serviceName: test-victoria-metrics-scott-victoria-metrics-single-server
  selector:
    matchLabels: 
      app: server
      app.kubernetes.io/instance: test-victoria-metrics-scott
      app.kubernetes.io/name: victoria-metrics-single
  template:
    metadata:
      labels: 
        app: server
        app.kubernetes.io/instance: test-victoria-metrics-scott
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-single
        app.kubernetes.io/version: v1.136.0
        helm.sh/chart: victoria-metrics-single-0.31.0
    spec:
      serviceAccountName: test-victoria-metrics-scott-victoria-metrics-single-server
      automountServiceAccountToken: true
      securityContext: 
        {}
      containers:
        - name: vmsingle
          securityContext: 
            {}
          image: victoriametrics/victoria-metrics:v1.136.0
          imagePullPolicy: IfNotPresent
          args: 
            - --envflag.enable
            - --envflag.prefix=VM_
            - --httpListenAddr=:8428
            - --loggerFormat=json
            - --retentionPeriod=1
            - --storageDataPath=/storage
          ports:
            - name: http
              containerPort: 8428
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe: 
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 5
          volumeMounts:
            - name: server-volume
              mountPath: /storage
            
      terminationGracePeriodSeconds: 60
      volumes:
        
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: server-volume
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
