---
# Source: grafana-taylor/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-10.5.15
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana
    app.kubernetes.io/version: "12.3.1"
subjects:
  - kind: ServiceAccount
    name: test-grafana
    namespace: test-taylor-monitoring
roleRef:
  kind: ClusterRole
  name: test-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
