---
# Source: grafana-taylor/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: test-grafana
    app.kubernetes.io/version: "12.3.0"
  name: test-grafana-clusterrole
rules: []
