---
# Source: grafana-taylor/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
  namespace: taylor-monitoring
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "12.3.0"
rules: []
